# Generated by Django 3.2.7 on 2021-10-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_pates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pates',
            new_name='Pasta',
        ),
    ]
